# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# (GHC 8.8.4)
resolver: lts-16.17

packages:
  - '.'

extra-deps: []
# - hakyll-4.13.4.1

flags: {}
