# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# (GHC 8.6.5)
resolver: lts-14.16

packages:
  - '.'

extra-deps:
  - hakyll-4.13.0.1

flags: {}
