# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# (GHC 8.8.2)
resolver: lts-15.1

packages:
  - '.'

extra-deps:
  - hakyll-4.13.1.0

flags: {}
