# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# (GHC 8.6.4)
resolver: lts-13.17

packages:
  - '.'

extra-deps:
  - hakyll-4.12.5.1
  - lrucache-1.2.0.1

flags: {}
